print ("Welcome to FIBO XPrize Software Team!")
print ("Blink is on the team. <3")
print ("Julong is on the team. <3")
print ("Wawa is on the team. <3")
print ("TsBeNz is on the team. <3")
print ("HimeChan0048 is on the team. <3")
print ("worachit is on the team. (●´ω｀●)")
print ("amejiyo is on the team. <3")
print ("ninwara123 is on the team. <3")
print ("worathum is on the team")
print ("MosMotov is Smart, Handsome and on the team now! <3 y")
print ("SuaEngineer_space is on the team. <3")
print ("Teeeeeeeeeeeeeeee is on the team. <3")