print ("Welcome to FIBO XPrize Software Team!")
print ("Blink is on the team. <3")
print ("Julong is on the team. <3")
print ("Wawa is on the team. <3")
print ("TsBeNz is on the team. <3")
print ("HimeChan0048 is on the team. <3")
