// Generated by gencpp from file open_base/KinematicsInverse.msg
// DO NOT EDIT!


#ifndef OPEN_BASE_MESSAGE_KINEMATICSINVERSE_H
#define OPEN_BASE_MESSAGE_KINEMATICSINVERSE_H

#include <ros/service_traits.h>


#include <open_base/KinematicsInverseRequest.h>
#include <open_base/KinematicsInverseResponse.h>


namespace open_base
{

struct KinematicsInverse
{

typedef KinematicsInverseRequest Request;
typedef KinematicsInverseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct KinematicsInverse
} // namespace open_base


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::open_base::KinematicsInverse > {
  static const char* value()
  {
    return "cb684d22809e19793d1c5c527b5f8cf4";
  }

  static const char* value(const ::open_base::KinematicsInverse&) { return value(); }
};

template<>
struct DataType< ::open_base::KinematicsInverse > {
  static const char* value()
  {
    return "open_base/KinematicsInverse";
  }

  static const char* value(const ::open_base::KinematicsInverse&) { return value(); }
};


// service_traits::MD5Sum< ::open_base::KinematicsInverseRequest> should match 
// service_traits::MD5Sum< ::open_base::KinematicsInverse > 
template<>
struct MD5Sum< ::open_base::KinematicsInverseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::open_base::KinematicsInverse >::value();
  }
  static const char* value(const ::open_base::KinematicsInverseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::open_base::KinematicsInverseRequest> should match 
// service_traits::DataType< ::open_base::KinematicsInverse > 
template<>
struct DataType< ::open_base::KinematicsInverseRequest>
{
  static const char* value()
  {
    return DataType< ::open_base::KinematicsInverse >::value();
  }
  static const char* value(const ::open_base::KinematicsInverseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::open_base::KinematicsInverseResponse> should match 
// service_traits::MD5Sum< ::open_base::KinematicsInverse > 
template<>
struct MD5Sum< ::open_base::KinematicsInverseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::open_base::KinematicsInverse >::value();
  }
  static const char* value(const ::open_base::KinematicsInverseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::open_base::KinematicsInverseResponse> should match 
// service_traits::DataType< ::open_base::KinematicsInverse > 
template<>
struct DataType< ::open_base::KinematicsInverseResponse>
{
  static const char* value()
  {
    return DataType< ::open_base::KinematicsInverse >::value();
  }
  static const char* value(const ::open_base::KinematicsInverseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPEN_BASE_MESSAGE_KINEMATICSINVERSE_H
