# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from open_base/MovementBezier.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class MovementBezier(genpy.Message):
  _md5sum = "ded95d34881d8c480a26fcec4fc049df"
  _type = "open_base/MovementBezier"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 frame
geometry_msgs/Pose2D[] targetTranslation
float64[] targetRotation
float64 step
bool offsetTraslation
bool offsetRotation

================================================================================
MSG: geometry_msgs/Pose2D
# Deprecated
# Please use the full 3D pose.

# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.

# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.


# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta
"""
  __slots__ = ['frame','targetTranslation','targetRotation','step','offsetTraslation','offsetRotation']
  _slot_types = ['uint8','geometry_msgs/Pose2D[]','float64[]','float64','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       frame,targetTranslation,targetRotation,step,offsetTraslation,offsetRotation

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MovementBezier, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.frame is None:
        self.frame = 0
      if self.targetTranslation is None:
        self.targetTranslation = []
      if self.targetRotation is None:
        self.targetRotation = []
      if self.step is None:
        self.step = 0.
      if self.offsetTraslation is None:
        self.offsetTraslation = False
      if self.offsetRotation is None:
        self.offsetRotation = False
    else:
      self.frame = 0
      self.targetTranslation = []
      self.targetRotation = []
      self.step = 0.
      self.offsetTraslation = False
      self.offsetRotation = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_B().pack(self.frame))
      length = len(self.targetTranslation)
      buff.write(_struct_I.pack(length))
      for val1 in self.targetTranslation:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      length = len(self.targetRotation)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.targetRotation))
      _x = self
      buff.write(_get_struct_d2B().pack(_x.step, _x.offsetTraslation, _x.offsetRotation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.targetTranslation is None:
        self.targetTranslation = None
      end = 0
      start = end
      end += 1
      (self.frame,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.targetTranslation = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.targetTranslation.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.targetRotation = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 10
      (_x.step, _x.offsetTraslation, _x.offsetRotation,) = _get_struct_d2B().unpack(str[start:end])
      self.offsetTraslation = bool(self.offsetTraslation)
      self.offsetRotation = bool(self.offsetRotation)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_B().pack(self.frame))
      length = len(self.targetTranslation)
      buff.write(_struct_I.pack(length))
      for val1 in self.targetTranslation:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
      length = len(self.targetRotation)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.targetRotation.tostring())
      _x = self
      buff.write(_get_struct_d2B().pack(_x.step, _x.offsetTraslation, _x.offsetRotation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.targetTranslation is None:
        self.targetTranslation = None
      end = 0
      start = end
      end += 1
      (self.frame,) = _get_struct_B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.targetTranslation = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.targetTranslation.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.targetRotation = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      _x = self
      start = end
      end += 10
      (_x.step, _x.offsetTraslation, _x.offsetRotation,) = _get_struct_d2B().unpack(str[start:end])
      self.offsetTraslation = bool(self.offsetTraslation)
      self.offsetRotation = bool(self.offsetRotation)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_d2B = None
def _get_struct_d2B():
    global _struct_d2B
    if _struct_d2B is None:
        _struct_d2B = struct.Struct("<d2B")
    return _struct_d2B
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
