// Generated by gencpp from file neo_msgs/LCDOutput.msg
// DO NOT EDIT!


#ifndef NEO_MSGS_MESSAGE_LCDOUTPUT_H
#define NEO_MSGS_MESSAGE_LCDOUTPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace neo_msgs
{
template <class ContainerAllocator>
struct LCDOutput_
{
  typedef LCDOutput_<ContainerAllocator> Type;

  LCDOutput_()
    : msg_line()  {
    }
  LCDOutput_(const ContainerAllocator& _alloc)
    : msg_line(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_line_type;
  _msg_line_type msg_line;





  typedef boost::shared_ptr< ::neo_msgs::LCDOutput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::neo_msgs::LCDOutput_<ContainerAllocator> const> ConstPtr;

}; // struct LCDOutput_

typedef ::neo_msgs::LCDOutput_<std::allocator<void> > LCDOutput;

typedef boost::shared_ptr< ::neo_msgs::LCDOutput > LCDOutputPtr;
typedef boost::shared_ptr< ::neo_msgs::LCDOutput const> LCDOutputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::neo_msgs::LCDOutput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::neo_msgs::LCDOutput_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace neo_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'neo_msgs': ['/home/xprize/Bally_Workspace/src/neo_driver/neo_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::neo_msgs::LCDOutput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::neo_msgs::LCDOutput_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_msgs::LCDOutput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::neo_msgs::LCDOutput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_msgs::LCDOutput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::neo_msgs::LCDOutput_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::neo_msgs::LCDOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a223a10d4aa8b3dc5e74a6c05e5047f2";
  }

  static const char* value(const ::neo_msgs::LCDOutput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa223a10d4aa8b3dcULL;
  static const uint64_t static_value2 = 0x5e74a6c05e5047f2ULL;
};

template<class ContainerAllocator>
struct DataType< ::neo_msgs::LCDOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "neo_msgs/LCDOutput";
  }

  static const char* value(const ::neo_msgs::LCDOutput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::neo_msgs::LCDOutput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string msg_line 	#in mode 1 msg_lines size is limited to 20 chars\n"
"			#in mode 2 msg_lines size is limited to 60 chars\n"
;
  }

  static const char* value(const ::neo_msgs::LCDOutput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::neo_msgs::LCDOutput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg_line);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LCDOutput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::neo_msgs::LCDOutput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::neo_msgs::LCDOutput_<ContainerAllocator>& v)
  {
    s << indent << "msg_line: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg_line);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NEO_MSGS_MESSAGE_LCDOUTPUT_H
